export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const CHANGE_TAB = 'CHANGE_TAB';

export const PROCESS_IMAGE_START = 'camera/PROCESS_IMAGE_START';
export const PROCESS_IMAGE_SUCCESS = 'camera/PROCESS_IMAGE_SUCCESS';
export const PROCESS_IMAGE_ERROR = 'camera/PROCESS_IMAGE_ERROR';

export const TAKE_PHOTO_SUCCESS = 'camera/TAKE_PHOTO_SUCCESS';
